server {
    listen 80;
    listen [::]:80;
    server_name btd.nostrabotus.com;

    root /opt/nba-favorites;
    index index.html;

    location = / {
        return 301 /dashboard/;
    }

    location / {
        try_files $uri $uri/ =404;
        add_header Cache-Control "no-cache" always;
    }
}
